
export const PUT_BROTHERHOOD_REQUEST = 'PUT_BROTHERHOOD_REQUEST';
export const PUT_BROTHERHOOD_SUCCESS = 'PUT_BROTHERHOOD_SUCCESS';
export const PUT_BROTHERHOOD_FAILURE = 'PUT_BROTHERHOOD_FAILURE';

export const GET_ALL_BROTHERHOOD_REQUEST = 'GET_ALL_BROTHERHOOD_REQUEST';
export const GET_ALL_BROTHERHOOD_SUCCESS = 'GET_ALL_BROTHERHOOD_SUCCESS';
export const GET_ALL_BROTHERHOOD_FAILURE = 'GET_ALL_BROTHERHOOD_FAILURE';

export const DELETE_BROTHERHOOD_REQUEST = 'DELETE_BROTHERHOOD_REQUEST';
export const DELETE_BROTHERHOOD_SUCCESS = 'DELETE_BROTHERHOOD_SUCCESS';
export const DELETE_BROTHERHOOD_FAILURE = 'DELETE_BROTHERHOOD_FAILURE';

export const GET_BROTHERHOOD_REQUEST = 'GET_BROTHERHOOD_REQUEST';
export const GET_BROTHERHOOD_SUCCESS = 'GET_BROTHERHOOD_SUCCESS';
export const GET_BROTHERHOOD_FAILURE = 'GET_BROTHERHOOD_FAILURE';

export const POST_BROTHERHOOD_REQUEST = 'POST_BROTHERHOOD_REQUEST';
export const POST_BROTHERHOOD_SUCCESS = 'POST_BROTHERHOOD_SUCCESS';
export const POST_BROTHERHOOD_FAILURE = 'POST_BROTHERHOOD_FAILURE';